export const SELECT_SECTION = "SECTION/SELECT_SECTION";
export const ADD_SECTION = "SECTION/CREATE_SECTION";
export const CHANGE_SECTION = "SECTION/CHANGE_SECTION";
export const REMOVE_SECTION = "SECTION/REMOVE_SECTION";
export const SELECT_WIDGET = "SECTION/SELECT_WIDGET";
export const ADD_WIDGET = "SECTION/ADD_WIDGET";
export const CHANGE_WIDGET = "SECTION/CHANGE_WIDGET";
export const REMOVE_WIDGET = "SECTION/REMOVE_WIDGET";
export const ADD_COLUMNS = "SECTION/ADD_COLUMNS";
export const REMOVE_COLUMNS = "SECTION/REMOVE_COLUMNS";
export const CHANGE_COLUMNS = "SECTION/CHANGE_COLUMNS";
export const IMPORT_STRUCTURE = "SECTION/IMPORT_STRUCTURE";

export const CHANGE_SETTINGS = "SETTINGS/CHANGE_SETTINGS";

export const LOADER = "APP/LOADER";
export const SHOW_ALERT = "APP/SHOW_ALERT";
export const HIDE_ALERT = "APP/HIDE_ALERT";
