export const ADD_SECTION = "SECTION/CREATE_SECTION";
export const SELECT_SECTION = "SECTION/SELECT_SECTION";
export const SELECT_WIDGET = "SECTION/SELECT_WIDGET";
export const ADD_WIDGET = "SECTION/ADD_WIDGET";
export const CHANGE_WIDGET = "SECTION/CHANGE_WIDGET";

export const LOADER = "APP/LOADER";
export const SHOW_ALERT = "APP/SHOW_ALERT";
export const HIDE_ALERT = "APP/HIDE_ALERT";
